name: Deploy FastAPI to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      # Package application (zip for Lambda or build Docker image)
      - name: Package Lambda
        run: |
          mkdir package
          cp -r main.py ./package/
          cd package
          pip3 install -r requirements.txt
          zip -r ../restful-notes.zip .
          cd ..

      # Configure AWS CLI
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      # Deploy to AWS Lambda
      # - name: Deploy Lambda Function
      #   run: |
      #     aws lambda update-function-code \
      #       --function-name restful-notes \
      #       --zip-file fileb://restful-notes.zip

      # Clean up package folder
      # - name: Remove package folder
      #   run: |
      #     rm -rf package
