name: Deploy FastAPI to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # Install Serverless Framework
      - name: Install Serverless
        run: npm install -g serverless

      # Install dependencies
      - name: Install dependencies
        run: |
          pip3 install --no-cache-dir -r requirements.txt
          pip3 install serverless-python-requirements

      # Deploy to AWS Lambda
      - name: Deploy to AWS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          serverless deploy
